[build]
  command = "rustup default stable && rustup target add wasm32-unknown-unknown && cargo install --locked trunk && cd frontend && trunk build --release"
  publish = "frontend/dist"

[build.environment]
  API_URL = "https://sueca-4c4k.onrender.com"
